services:
  - type: web
    name: dash-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn multi_app:server --workers 1
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
